### ISSUE TITLE
Anagrafica Cassiere quale criterio di ricerca utilizzare?

### ISSUE THREAD

**Issue by MatteoPalombo99** [luca-lezzerini/scarsefour#10]
Quale criterio di ricerca utilizzare con i cassieri che hanno : nome, cognome e codice fiscale?

**Comment by luca-lezzerini** [comment]
cognome o nome like o codice fiscale esatto

**Comment by MatteoPalombo99** [comment]
risolto al commit d438a234e811f5a0e012cba16ce89b6689fb1865
