### ISSUE TITLE
Hispanici fermi in attesa di nuovi ticket

### ISSUE THREAD

**Issue by capponiFelice92** [luca-lezzerini/scarsefour#12]
Da progetto non è chiaro come procedere dopo che le anagrafiche sono pronte.

Uno dei passi da fare sembrerebbe creare un nuovo automa che gestisca la UI della cassa, ma: 
Questo nuovo automa condivide qualcosa con l'automa di crud(Es. interfaccia state, interfaccia event, la classe Automa stessa)?

**Comment by luca-lezzerini** [comment]
Se avete finito i ticket state fermi. Domani vi spiego gli altri UC. Se non trovo errori nei vostri programmini ...
