### ISSUE TITLE
Errore

### ISSUE THREAD

**Issue by ValeriaCom** [luca-lezzerini/scarsefour#21]
Quando andiamo a scrivere gli eventi nel ts, ecco l'errore che ci compare:
![erroridashboard](https://user-images.githubusercontent.com/78487304/112053556-c85d3f00-8b54-11eb-93c8-0bcbcc8fc193.PNG)

L'errore in "VediPrezzoEvent" riporta la seguente citazione(così come tutti gli altri Event) : L'argomento di tipo 'VediPrezzoEvent' non è assegnabile al parametro di tipo 'Event'.
  Nel tipo 'VediPrezzoEvent' mancano le proprietà seguenti del tipo 'Event': bubbles, cancelBubble, cancelable, composed e altre 18.ts(2345).

Abbiamo controllato gli import varie volte e non ci sembra di trovare nessun errore. Non sappiamo quindi come procedere.

**Comment by luca-lezzerini** [comment]
In automa.ts dovete importare Event

**Comment by ValeriaCom** [comment]
Ok, grazie.
