### ISSUE TITLE
Implementare UC Anagrafica Cassiere

### ISSUE THREAD

**Issue by luca-lezzerini** [luca-lezzerini/scarsefour#6]

**Comment by daniele-bit** [comment]
Implementato scheletro Anagrafica Sconti lato server.
inserito metodo main nel Run del progetto al commit 66dbb8710f5885317b7c703fc69efcc3372b1440

**Comment by MatteoPalombo99** [comment]
completato al commit 67820121b4d73621b010d3f8eb598186ad2e621d

**Comment by MatteoPalombo99** [comment]
5e26143532b59ac1353e47ce9a73262bae055727
