### ISSUE TITLE
Implementare UC Anagrafica Casse

### ISSUE THREAD

**Issue by luca-lezzerini** [luca-lezzerini/scarsefour#7]

**Comment by matteo2025** [comment]
prima versione commit: 1034988f2a547c26e8dc0f3c79db963e10c72a9b

**Comment by nicoloabatecola** [comment]
Implementata eliminazione al commit: feb1e688aac29045820f0364bb19c44a72e764b3

**Comment by matteo2025** [comment]
implementata modifica al commit: a4e8c74154c3f1711368d5a08d81c8f1550c84b5

**Comment by capponiFelice92** [comment]
completato al commit ab55b8498ada9970e49c4b30406a0887bacebd11

**Comment by capponiFelice92** [comment]
3759cb0f1c52beea06f8cb76412f54af8db5aba0
