### ISSUE TITLE
Implementare UC Anagrafica Sconti

### ISSUE THREAD

**Issue by luca-lezzerini** [luca-lezzerini/scarsefour#8]

**Comment by daniele-bit** [comment]
Implementato scheletro Anagrafica Sconti lato server.
inserito metodo main nel Run del progetto al commit 66dbb87

**Comment by daniele-bit** [comment]
79e40d4618c4692af19079370fdb6e12d29465d5

**Comment by marcobonaccorso** [comment]
Caso d'uso completato al commit b39494f848eb8e3d7542b009d07d68114d562a78
