### ISSUE TITLE
Creare foglio stile CSS 

### ISSUE THREAD

**Issue by luca-lezzerini** [luca-lezzerini/scarsefour#9]
Creare un foglio di stile CSS globale nel client (dentro app) chiamato theme.css.
Definire a piacere gli stili per:

titolo-grande
etichetta-testo
etichetta-bottone
bottone-attivo
bottone-disabilitato
campo-input
body
tabella
header-tabella
riga-tabella

**Comment by nicoloabatecola** [comment]
Implementata prima parte al commit: b4ec2d8b513fd332a963700804a29bc00500a35d

**Comment by nicoloabatecola** [comment]
Seconda parte al commit: 69312c1e4c7f6876de906b906c417040ff1f6fdc

**Comment by nicoloabatecola** [comment]
Risolto ticket al commit: 91b47b653af1b5e66f00de58d65638ce003860a1
